---

platform: linux

image_resource:
  type: docker-image
  source: {repository: 10.144.15.109/rjain/buildbox,  insecure_registries: ["10.144.15.109","10.144.15.109:443"]}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  OM_DECRYPTION_PWD:

inputs:
  - name: pcf-pipelines
  - name: tool-om

run:
  path: pcf-pipelines/tasks/config-opsman/task.sh
