groups: []
jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: elastic-runtime
    params:
      globs: []
- name: upgrade-tile
  plan:
  - aggregate:
    - get: pivnet-product
      params:
        globs:
        - '*pivotal'
      passed:
      - regulator
      resource: elastic-runtime
      trigger: true
    - do:
      - get: pcf-pipelines-tarball
      - config:
          image_resource:
            source:
              repository: cloudfoundry/cflinuxfs2
            type: docker-image
          inputs:
          - name: pcf-pipelines-tarball
          outputs:
          - name: pcf-pipelines
          platform: linux
          run:
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
            path: sh
        task: unpack-tarball
    - get: tool-om
      params:
        globs:
        - om-linux
    - get: stemcell-downloader
      params:
        globs:
        - stemcell-downloader-linux
  - file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: wait-opsman-clear
  - file: pcf-pipelines/tasks/upload-product/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      PIVNET_PRODUCT_NAME: elastic-runtime
    task: upload-tile
  - file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      PRODUCT_NAME: cf
    task: stage-tile
  - file: pcf-pipelines/tasks/upload-stemcell/task.yml
    params:
      IAAS_TYPE: {{iaas_type}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
      PRODUCT: cf
    task: upload-stemcell
  - file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: apply-changes
resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
resources:
- name: pcf-pipelines-tarball
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: v0.11.0
  type: pivnet
- name: tool-om
  source:
    access_token: {{github_token}}
    repository: om
    user: pivotal-cf
  type: github-release
- check_every: {{pivnet_poll_interval}}
  name: elastic-runtime
  source:
    api_token: {{pivnet_token}}
    product_slug: elastic-runtime
    product_version: 1.9.*
    sort_by: semver
  type: pivnet
- name: stemcell-downloader
  source:
    access_token: {{github_token}}
    globs:
    - stemcell-downloader-linux
    repository: pcf-product-stemcell-downloader
    user: pivotal-cf
  type: github-release
- name: schedule
  source:
    days:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    interval: 30m
    location: America/Los_Angeles
    start: 12:00 AM
    stop: 11:59 PM
  type: time
