jobs:
- name: regulator
  plan:
  - get: schedule
    trigger: true
  - get: pivnet-opsmgr
    params:
      globs: []
- name: upgrade-opsmgr
  plan:
  - aggregate:
    - get: pivnet-opsmgr
      params:
        globs:
        - '*AWS.yml'
      passed:
      - regulator
      trigger: true
    - get: tool-cliaas
      params:
        globs:
        - '*linux*'
    - do:
      - get: pcf-pipelines-tarball
      - config:
          image_resource:
            source:
              repository: cloudfoundry/cflinuxfs2
            type: docker-image
          inputs:
          - name: pcf-pipelines-tarball
          outputs:
          - name: pcf-pipelines
          platform: linux
          run:
            args:
            - -c
            - tar -xvf pcf-pipelines-tarball/*.tgz
            path: sh
        task: unpack-tarball
    - get: tool-om
      params:
        globs:
        - '*linux*'
    - get: tool-pivnet-cli
      params:
        globs:
        - '*linux*'
  - file: pcf-pipelines/tasks/wait-opsman-clear/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: wait-opsman-clear
  - aggregate:
    - file: pcf-pipelines/tasks/export-opsmgr-settings/task.yml
      params:
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_SETTINGS_FILENAME: installation.zip
        OPSMAN_URI: {{opsman_uri}}
        OPSMAN_USERNAME: {{opsman_admin_username}}
      task: export-opsmgr-settings
    - file: pcf-pipelines/tasks/export-opsmgr-diagnostic-report/task.yml
      params:
        OPSMAN_PASSWORD: {{opsman_admin_password}}
        OPSMAN_URI: {{opsman_uri}}
        OPSMAN_USERNAME: {{opsman_admin_username}}
      task: exported-opsmgr-diagnostic-report
  - file: pcf-pipelines/tasks/create-cliaas-config-aws/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{aws_access_key_id}}
      AWS_REGION: {{aws_region}}
      AWS_SECRET_ACCESS_KEY: {{aws_secret_access_key}}
      AWS_VPC_ID: {{aws_vpc_id}}
    task: create-cliaas-config
  - file: pcf-pipelines/tasks/replace-vm/task.yml
    params:
      VM_IDENTIFIER: {{existing_opsman_vm_name}}
    task: replace-opsman-vm
  - file: pcf-pipelines/tasks/import-opsmgr-settings/task.yml
    params:
      OPSMAN_PASSPHRASE: {{opsman_passphrase}}
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_SETTINGS_FILENAME: installation.zip
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: import-opsmgr-settings
  - file: pcf-pipelines/tasks/download-pivnet-stemcells/task.yml
    params:
      API_TOKEN: {{pivnet_token}}
      IAAS_TYPE: aws
    task: download-stemcells
  - file: pcf-pipelines/tasks/restore-stemcells/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: restore-stemcells
  - file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_PASSWORD: {{opsman_admin_password}}
      OPSMAN_TIMEOUT: {{opsman_timeout_seconds}}
      OPSMAN_URI: {{opsman_uri}}
      OPSMAN_USERNAME: {{opsman_admin_username}}
    task: apply-changes
  serial: true
resource_types:
- name: pivnet
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
  type: docker-image
resources:
- check_every: {{check_new_opsman_every}}
  name: pivnet-opsmgr
  source:
    api_token: {{pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver
  type: pivnet
- name: tool-cliaas
  source:
    access_token: {{github_token}}
    repository: cliaas
    user: pivotal-cf
  type: github-release
- name: tool-om
  source:
    access_token: {{github_token}}
    repository: om
    user: pivotal-cf
  type: github-release
- name: tool-pivnet-cli
  source:
    access_token: {{github_token}}
    repository: pivnet-cli
    user: pivotal-cf
  type: github-release
- name: pcf-pipelines-tarball
  source:
    api_token: {{pivnet_token}}
    product_slug: pcf-automation
    product_version: v0.11.0
  type: pivnet
- name: schedule
  source:
    days:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    interval: 30m
    location: America/Los_Angeles
    start: 12:00 AM
    stop: 11:59 PM
  type: time
