---

platform: linux

image_resource:
  type: docker-image
  source: {repository: 10.144.15.109/rjain/buildbox,  insecure_registries: ["10.144.15.109","10.144.15.109:443"]}

params:
  OPS_MGR_HOST:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:

inputs:
  - name: pivnet-product
  - name: pcf-pipelines
  - name: tool-om
  - name: pivnet-cli

run:
  path: pcf-pipelines/tasks/upload-product-and-stemcell/task.sh
