---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker-gcp

inputs:
- name: pcf-pipelines 

params:
  pcf_ert_domain:

run:
  path: pcf-pipelines/tasks/install-pcf-gcp/check-opsman-dns.sh
