---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker-gcp

inputs:
- name: pcf-pipelines 
- name: pivnet-opsmgr
- name: tfstate-version

outputs:
- name: create-infrastructure-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:
  GCP_ZONE_1:
  GCP_ZONE_2:
  GCP_ZONE_3:
  GCP_RESOURCE_PREFIX:
  PCF_ERT_DOMAIN:
  PCF_ERT_SSL_CERT:
  PCF_ERT_SSL_KEY:
  ERT_SQL_DB_USERNAME:
  ERT_SQL_DB_PASSWORD:

run:
  path: pcf-pipelines/tasks/install-pcf-gcp/create-infrastructure.sh
