---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker-gcp

inputs:
- name: pcf-pipelines 
- name: tfstate
- name: tfstate-version

outputs:
- name: wipe-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: pcf-pipelines/tasks/install-pcf-gcp/wipe-env.sh
