---

platform: linux

image_resource:
  type: docker-image
  source: {repository: 10.144.15.109/rjain/buildbox,  insecure_registries: ["10.144.15.109","10.144.15.109:443"]}

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  GOVC_HOST:
  OPS_MGR_HOST:
  OPS_MGR_SSH_PWD:
  OM_NTP_SERVERS:
  OM_DNS_SERVERS:
  OM_GATEWAY:
  OM_NETMASK:
  OM_IP:
  OM_VM_NETWORK:
  OM_VM_NAME:
  OM_RESOURCE_POOL:
  OM_DISK_TYPE:
  OM_VM_POWER_STATE:


inputs:
  - name: pivnet-opsman-product
  - name: pcf-pipelines
  - name: govc

run:
  path: pcf-pipelines/tasks/import-opsman/task.sh
